### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Demro** [Archotech/TTR24-Feedback#10]
Subject: Server error
Version: 0.4.43
Platform: Windows 10
Severity: Critical

Steps to Reproduce:
Join to the server Sigma and you get the error

Expected Behavior:
Update and fix the error.

Actual Behavior:
Still the error.

Screenshot/Video of the error message:
![image](https://github.com/Archotech/TTR24-Feedback/assets/54320957/e02a49c4-95ba-4860-8d93-6eda5ac2dac3)
![20240401175101_1](https://github.com/Archotech/TTR24-Feedback/assets/54320957/a1f4e5d6-a75a-423d-8edb-13da7895d60a)

**Comment by Sont3k** [comment]
последствие другой ошибки, просто закрываю
