### ISSUE TITLE
[Bug]: SCP-173 causes damage to itself

### ISSUE THREAD

**Issue by RiFFyg** [Archotech/TTR24-Feedback#100]
### Steps To Reproduce

1. Blow for the role 173
2. Each blow deals itself about 1/4 of the total health.

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/173466992/61c592a0-9169-4a2b-883c-6e991e2cb493

### Expected Behavior

Damage should not be inflicted 173 from your own blows

### OS

Windows 11

### Version

0.5.409

**Comment by DecafRx** [comment]
https://youtu.be/kTSKqv4DkdI

**Comment by Sont3k** [comment]
Was fixed here with a high chance: https://github.com/Archotech/TTR24/pull/1291

**Comment by DecafRx** [comment]
https://github.com/Archotech/TTR24-Feedback/assets/140116455/31bf9ccc-c848-48e7-a3f1-0ac52b422337

Баг все еще остался

**Comment by Sont3k** [comment]
https://github.com/Archotech/TTR24/pull/1305

**Comment by belplaton** [comment]
Там ошибка в том, что CastObjectChecker вовзращает не тот список. Дело не в Attack Ability

**Comment by DecafRx** [comment]
Пофикшено
