### ISSUE TITLE
[Bug]: Phantom objects in the hands

### ISSUE THREAD

**Issue by RiFFyg** [Archotech/TTR24-Feedback#101]
### Steps To Reproduce

1. Pick up an object.
2. Throw it on G and remove it from your hands at the same time.
3. If the item is active, it can be used

### Actual Behavior

The weapon shoots, does not cause damage

https://github.com/Archotech/TTR24-Feedback/assets/173466992/305202b9-d773-4411-9aa9-3914ec3a2b2e

### Expected Behavior

The item should not remain in your hands

### OS

Windows 11

### Version

0.5.410

**Comment by DecafRx** [comment]
Fixed

**Comment by DecafRx** [comment]
https://github.com/user-attachments/assets/12c1b406-d51c-418e-9033-e76884d913eb

Баг остался
Для воспроизведения надо 
Нажать на слот оружия (1/2/3), и выкинуть (На G) сделать надо ПОЧТИ одновременно, первым должно все же быть нажато на слот оружия
