### ISSUE TITLE
[Bug]: Flashbangs didnt working

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#103]
### Steps To Reproduce

1 Взять светошумовую гранату
2 Кинуть ее

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/5e6fd936-cdff-4628-b623-6b3fc30a98b0

Светошумовая граната издает звук взрыва, но эффекта нету

### Expected Behavior

Эффект ослепления/оглушения должен быть

### OS

Windows 10

### Version

0.5.410

**Comment by belplaton** [comment]
Only after local objects pull request.

Нужно будет заменить в префабе M84 Engaged слои в FlashChecker и StunChecker на WorldObjectAndPlayer, т.к. локальный слой будет полностью удален

**Comment by DecafRx** [comment]
It works now
- fixed
