### ISSUE TITLE
[Bug]: The elevator affects the player who got out of it

### ISSUE THREAD

**Issue by RiFFyg** [Archotech/TTR24-Feedback#106]
### Steps To Reproduce

1. Enter the elevator.
2. Press the button.
3. Run out of the elevator.

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/173466992/2fc2bc49-7720-407c-9f89-d1db7ca35a70

### Expected Behavior

An elevator should not try to move a player

### OS

Windows 11

### Version

0.5.410

**Comment by DecafRx** [comment]
Баг остался, абсолютно такой же

**Comment by belplaton** [comment]
@Sont3k мб просто делать тада парентинг игрока к лифту при входе\выходе, а не только при старте езды? Ну по крайней мере анпарентинг когда покидает триггер обжект чекер, шоб этого не было

**Comment by Sont3k** [comment]
если при входе/выходе, то он мерцает сильно
так что лучше только при старте езды

этот баг полностью упирается в то, что игрок успевает выйти из зоны триггера и его не открепляет в итоге от лифта, и поэтому начинается колбас

**Comment by belplaton** [comment]
Не исправлено

**Comment by Sont3k** [comment]
![Image](https://github.com/Archotech/TTR24-Feedback/assets/40692222/87fdc752-7a6c-46c1-96d5-f7a2bfc45988)

**Comment by DecafRx** [comment]
Fixed

**Comment by DecafRx** [comment]
Пофикшено, когда выходишь из лифта то снимается эффект спуска/подьема
НО в лифте эффект (естественно) остается, и он дохуя мощный, что выталкивает тебя нахуй: 

https://github.com/user-attachments/assets/7d6dc557-9bb7-424c-b15c-d0555a9bc9eb

**Comment by DecafRx** [comment]
https://github.com/user-attachments/assets/53b47165-e8a7-4e11-b2d2-ad40e107676b

**Comment by DecafRx** [comment]
https://github.com/user-attachments/assets/b3727910-75b8-4403-aea7-3159c58d0dad

**Comment by DecafRx** [comment]
https://github.com/user-attachments/assets/7348395f-666b-405e-9a94-368ef3c49f9c

**Comment by Sont3k** [comment]
в общем да, я переделываю лифт на телепортацию всей кабинки вместо движения
визуально для игрока разницы будет ноль, а для нас это кучу геморроя с синхронизацией уберет

**Comment by belplaton** [comment]
Вроде бы пофиксил, теперь игроков не шатает туда-сюда, правда клиент становится невидимым, но это исправимо

**Comment by belplaton** [comment]
Практически исправлено, телепортация не нужна

**Comment by belplaton** [comment]
Теперь лифты ассигнят персонажей на клиенте и на сервере независимо друг от друга, но с учетом того, откуда именно идет синк передвижения (с клиента на сервер или с сервера на клиент)

**Comment by belplaton** [comment]
Так же была проблема с Триггер Обжект Чекером, в нем была поломанная логика, из-за чего стоило лишь одному объекту игрока покинуть зону триггера лифта, так весь идентити уже считался покинутым. (Поскольку только один объект и запоминался)
