### ISSUE TITLE
[Bug]: First connected player always be SCP

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#107]
### Steps To Reproduce

1. Зайти на сервер с другими игроками
2. Тот, кто раньше подключится, будет СЦП

### Actual Behavior

Сколько бы раунды не кончались и не начинались, за сцп будет спавнится ТОЛЬКО определенный игрок
Было проверенно на версии 410 и 411
Примерно 5 раундов все время за сцп спавнился один определенный человек

### Expected Behavior

Рандомно должно спавнить

### OS

Windows 10

### Version

0.5.411

**Comment by belplaton** [comment]
Как пример еще можно привести то, что если запускать паррель синк, то сцп всегда будет хост, т.к. он коннектится первым

**Comment by belplaton** [comment]
![Image](https://github.com/Archotech/TTR24-Feedback/assets/143908720/a7f402f0-4ef4-44e6-9a47-6862e89f038f)

**Comment by DecafRx** [comment]
![Image](https://github.com/user-attachments/assets/55096e6d-490c-4637-a92c-ce871d187cc7)
