### ISSUE TITLE
Слишком маленькая зона содержания

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#11]
Subject: Генерация зоны содержания
Version: 0.4.43
Platform: Windows 10
Severity: medium

Steps to Reproduce:
?

За 3 катки попалось 2 раза крайне мелкая зона содержания, во всех 3 каток не заспавнилась комната из главного меню

https://github.com/Archotech/TTR24-Feedback/assets/140116455/5fd1c82a-d88d-4abf-ab7c-81666f6a6066

**Comment by Sont3k** [comment]
это не баг, такое может быть
