### ISSUE TITLE
[Bug]: big doors vanishing when u trying to see it in some angles

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#113]
### Steps To Reproduce

Посмотри на круговую дверь под разными углами/ракурсами

### Actual Behavior

![image](https://github.com/user-attachments/assets/569ab2aa-c441-40eb-92dd-dd1fd847113c)
дверь пропадает

### Expected Behavior

Дверь не должна пропадатб

### OS

Windows 10

### Version

0 5 413

**Comment by AdobeFlex** [comment]
Это происходит не только с большими дверями, иногда это происходит  в упор с некоторыми локациями, обратите внимание на скриншот, локация не подгружается почти в упоре при взгляде в пол

![Image](https://github.com/user-attachments/assets/2e295f1c-a4ed-4f3f-bef5-bb62c65aa3ef)
