### ISSUE TITLE
[Bug]: u can take items through props

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#114]
### Steps To Reproduce

-

### Actual Behavior

![image](https://github.com/user-attachments/assets/1a26feb6-99f0-43af-82a8-de5b96fda028)

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.413

**Comment by belplaton** [comment]
Его коллайдер скорее всего просто проходит насквозь, т.к. этот баг не воспроизводится в других местах, а у этого пропа настройки корректны
