### ISSUE TITLE
[Bug]: Проблема с микрофоном

### ISSUE THREAD

**Issue by MrDemon768** [Archotech/TTR24-Feedback#121]
### Steps To Reproduce

1.Зайти в раунд

### Actual Behavior

Не работает микрофон

### Expected Behavior

Что бы работал микрафон

### OS

Windows 11

### Version

testing - Debug Build For Testers

### Additional Context

Игра под названием SCP: EVENT CLASSIFIED. Код ошибки: [Dissonance:Recording] (18:31:02:702) FMODMicrophoneInput: Inffucient buffer space to pump microphone

### Contact information

solomskyjd@gmail.com

**Comment by belplaton** [comment]
FMOD internal error, no need to fix
