### ISSUE TITLE
[Bug]: U can dupe trowable items

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#125]
### Steps To Reproduce

G + активация на лкм

### Actual Behavior

https://github.com/user-attachments/assets/1eeb3bdd-a33d-415e-8e0f-17d87ff8f7cb

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.415

### Additional Context

-

**Comment by RiFFyg** [comment]
And other activated items, like first aid kits

**Comment by DecafRx** [comment]
https://github.com/user-attachments/assets/bf985c2e-3c37-4a06-9e50-07f0cd266272

Not fixed
