### ISSUE TITLE
[BUG] Невозможная для игры карта

### ISSUE THREAD

**Issue by quesht** [Archotech/TTR24-Feedback#13]
Subject: Bug Report - генерация
Version: 0.4.43
Platform: Windows 10
Severity: Critical

Steps to Reproduce:
- Пройти во 2 зону

Expected Behavior:
- Карта сгенерировалась, и вы можете свободно сбежать или пройти в 3 или 1 зону.

Actual Behavior:
- Во 2 зоне карта сгенерировалась так что невозможно её пройти.

Screenshot/Video of the error message:
[Vid](https://youtu.be/fQTyI-EAjIE)

**Comment by Sont3k** [comment]
Это известно, поэтому просто закрываю
