### ISSUE TITLE
[Bug]: mtf eta10 uniform have strange hitbox

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#141]
### Steps To Reproduce

1spawn uniform via console

### Actual Behavior

it has strange physic and strange hitbox and icon in inventory like its personel uniform

https://github.com/user-attachments/assets/0c880b3c-b839-4f4a-a415-6908a8eaa639

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.419

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
