### ISSUE TITLE
[Bug]: scp 173 (his legs) (and any player in first person) desynchronization

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#144]
### Steps To Reproduce

1spawn as human
Try to walk

2 spawn as 172
Try to walk

### Actual Behavior

1 when u walking as human you got staggering/teleporting back/like a high ping

2 173 legs doesnt moving 

### Expected Behavior

-

### OS

Windows <10

### Version

0 4 421

**Comment by belplaton** [comment]
Это все находится на активной ветке, но не в мейне. Так и так проходит процесс изменения. Тесты нужны для сбора промежуточных результатов
