### ISSUE TITLE
[BUG] Плохой туалет (визуальный баг)

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#19]
Версия: 0 4 44
Дно туалета уходит в пол (Буквально в бетонный пол)
![image](https://github.com/Archotech/TTR24-Feedback/assets/140116455/f4fec0a8-fc6e-4c49-852e-ebde48252e73)

**Comment by JustMarfix** [comment]
@DecafRx Пожалуйста, используйте шаблон, чтобы мы могли правильно работать с багом.
