### ISSUE TITLE
[BUG] Предметы можно брать сквозь стены

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#20]
0 4 44
Казалось бы ничего страшного, не великий баг, но он полностью делает useless вот эту фигню:
![image](https://github.com/Archotech/TTR24-Feedback/assets/140116455/f8cbd604-8476-4f7a-857f-70e69e731cea)

**Comment by JustMarfix** [comment]
@DecafRx Пожалуйста, используйте шаблон, чтобы мы могли правильно работать с багом.
