### ISSUE TITLE
Кд ломание двери за 173 поломано

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#22]
https://github.com/Archotech/TTR24-Feedback/assets/140116455/a4ceffeb-35ed-4652-9757-1fefb3952b9b

Версия 0 4 44

**Comment by DecafRx** [comment]
К слову, каждый раз, когда я наводился на дверь - я кликал

**Comment by JustMarfix** [comment]
@DecafRx Пожалуйста, используйте шаблон, чтобы мы могли правильно работать с багом.
