### ISSUE TITLE
Баг с оптимизацией комнат

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#23]
### Steps To Reproduce

На любом публичном сервере переходить между комнатами

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/865693cf-4e94-4a20-a196-11666533ba7f

### Expected Behavior

Соседние комнаты должны быть визуально видны человеку

### OS

Windows <10

### Version

0.4.44

**Comment by Sont3k** [comment]
исправлено в 0.4.45
