### ISSUE TITLE
За 457 нельзя поглощать предметы

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#26]
### Steps To Reproduce

Заспавнится за 457
Попробовать сьесть предмет

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/31f7d987-1ff7-4c12-986b-4c679eda5e1a

За 457 нельзя поглощать предметы

### Expected Behavior

457 должен поглощать предметы

### OS

Windows <10

### Version

0.4.44

### Additional Context

На протяжении всего видео нажимал на кнопку поглощения предмета ЛКМ или ПКМ

**Comment by belplaton** [comment]
У тебя клавиша была F1, а не RBM, потому и не мог есть ты.

**Comment by belplaton** [comment]
@Sont3k  hi, can u close it plz?
