### ISSUE TITLE
[CRASH] <Fatal crash>

### ISSUE THREAD

**Issue by Demro** [Archotech/TTR24-Feedback#27]
Subject: Crash when I change the graphics
Version: 0.4.44
Platform: Windows 10
Severity: Several
Steps to Reproduce:
Play normally, then if you want to change the graphics, enter in setting menu and change the any option of graphic .

Expected Behavior:
Find and solve the problem of hte crash.
Actual Behavior:
The crash continue producing.

![image](https://github.com/Archotech/TTR24-Feedback/assets/54320957/72624dc7-cd02-4467-827a-58d46e947fb2)

https://github.com/Archotech/TTR24-Feedback/assets/54320957/646182e6-a4aa-46a0-9bba-3d0e1e30a688

**Comment by Sont3k** [comment]
you are just reloading the whole game when changing a graphics therefore it can freeze a game for a long time, this is not a crash, just long freeze, therefore can't be treated as a bug
