### ISSUE TITLE
[BUG] <стрельба сквозь текстуры и просмотр>

### ISSUE THREAD

**Issue by NekoHikka** [Archotech/TTR24-Feedback#28]
Работает на круглых лестницах

https://github.com/Archotech/TTR24-Feedback/assets/153106198/295f857b-eae7-4fac-bf03-f11c2653d5fa

**Comment by JustMarfix** [comment]
@NekoHikka пожалуйста, используйте шаблон при создании отчётов об ошибках.

**Comment by Sont3k** [comment]
@AdobeFlex нужен нормальный коллайдер на лестницу
