### ISSUE TITLE
[BUG] <Баг с отражениями>

### ISSUE THREAD

**Issue by NekoHikka** [Archotech/TTR24-Feedback#29]
Подходишь и багается отражение в комнате с реактором.
Графика: Медиум

https://github.com/Archotech/TTR24-Feedback/assets/153106198/11e33089-2653-4a83-8438-8ca60a00ca01

**Comment by JustMarfix** [comment]
@NekoHikka пожалуйста, используйте шаблон при создании отчётов об ошибках.
