### ISSUE TITLE
[Bug]: <Игрок застрял в дверном проёме/стене>

### ISSUE THREAD

**Issue by KatieNow** [Archotech/TTR24-Feedback#30]
### Steps To Reproduce

1. Пройти через дверной проём
2. Застрять :)

### Actual Behavior

Человек застревает над проходом

### Expected Behavior

Человек спокойно проходит через дверной проём

### OS

Windows 11

### Version

v0.4.45

### Additional Context

https://github.com/Archotech/TTR24-Feedback/assets/167201997/6941f4c6-03d2-48a5-89dc-0b81763e2914

### Contact information

m0nashhkka_kate

**Comment by belplaton** [comment]
ВХЗАХВЗХАЗВХАВ
