### ISSUE TITLE
[Bug]: Дублирование игроков в консоль и список игроков

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#54]
### Steps To Reproduce

Умереть играя за 1 класс
Возрадится за другой

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/f95d9298-1526-458f-923d-1705c6c18a85

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.4

**Comment by DecafRx** [comment]
https://github.com/Archotech/TTR24-Feedback/assets/140116455/32e7efde-4ef5-4a28-965f-d4a8153cfff2

**Comment by Sont3k** [comment]
исправлено
