### ISSUE TITLE
[Bug]: баг со спавном

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#56]
### Steps To Reproduce

-

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/3830ba61-651d-4f04-8498-40bc7f0249b5

Стартанулся раунд, фигово заспавнился

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.4

**Comment by DecafRx** [comment]
https://github.com/Archotech/TTR24-Feedback/assets/140116455/4a4b1d9b-c1a2-46ca-9357-58078c3bbe14

**Comment by DecafRx** [comment]
[Player.log](https://github.com/Archotech/TTR24-Feedback/files/15210191/Player.log)

**Comment by DecafRx** [comment]
Причем это происходит на локальном сервере, к которому я зашел
Когда свой собственный хостчу, то у меня все нормально

**Comment by Sont3k** [comment]
исправлено
