### ISSUE TITLE
[Bug]: Баги со спавном сцп предметов

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#58]
### Steps To Reproduce

-

### Actual Behavior

![image](https://github.com/Archotech/TTR24-Feedback/assets/140116455/6f6cf163-1a4c-42df-89f6-1152905a6c10)
![image](https://github.com/Archotech/TTR24-Feedback/assets/140116455/46961f69-d90c-46e9-888c-ede46ec77f4b)

(На одной локации заспавнились одинаковые сцп (3 сцп в 1 комнате и 2 в другой)

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.4 (new)

**Comment by DecafRx** [comment]
![image](https://github.com/Archotech/TTR24-Feedback/assets/140116455/2ea2936d-5f23-42af-a38c-1bbc0073fb46)
И еще

**Comment by Sont3k** [comment]
исправлено
