### ISSUE TITLE
[Bug]: Баг генерации (локация в локации)

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#60]
### Steps To Reproduce

-

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/8e8d0fe2-cd5d-4e86-aa75-cd0e9b01414d

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.4 (5/6/2024)

**Comment by DecafRx** [comment]
https://github.com/Archotech/TTR24-Feedback/assets/140116455/659b3dfd-435d-4129-bc1d-8995eda4a9e0


https://github.com/Archotech/TTR24-Feedback/assets/140116455/39de8c30-d051-4646-b5f7-a4b6f9b6f68c


0.5.4 (5/11/2024) Баг все еще актуален

**Comment by belplaton** [comment]
.

**Comment by belplaton** [comment]
Хз почему, но не могу ассигнуть себя и прикрепить ветку.
@Sont3k  [https://github.com/Archotech/TTR24/pull/1172](url)
