### ISSUE TITLE
[Bug]: Сервер конфиг не сохраняется

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#61]
### Steps To Reproduce

Открыть server_config.json
Внести туда например свой стим айди 64
Сохраняем файл

### Actual Behavior

После захода в игру и попытки ввести любую команду 
Будет ошибка:
![image](https://github.com/Archotech/TTR24-Feedback/assets/140116455/01b5c478-b90b-4cff-9b3f-24dce719b57e)

проверяем снова server_config.json - там ничего не сохранилось, сбросилось до первоначальной настройки

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.4 (5/11/2024)

**Comment by Sont3k** [comment]
исправлено
