### ISSUE TITLE
[Bug]: Перемешанный/сломанный перевод

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#62]
### Steps To Reproduce

Выбрать любой язык в меню (К примеру я выбрал Русский, а позже украинский)
Зайти в игру (катку)
Открыть инвентарь

### Actual Behavior

![image](https://github.com/Archotech/TTR24-Feedback/assets/140116455/5df3a35d-99bb-4072-9b95-6dc8961c85e7)
![image](https://github.com/Archotech/TTR24-Feedback/assets/140116455/2c5c74f4-4e90-4423-ae21-7f8a6a82ae92)

Слоты под одежду написаны на английском
Кровь и боль написаны на английском

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.4 (5/11/2024)

**Comment by Sont3k** [comment]
исправлено
