### ISSUE TITLE
[Bug]: Баг с лифтом в телепортатор

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#70]
### Steps To Reproduce

Вызвать лифт который ведет в телепорт в зоне содержания

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/ccab88dc-b66e-4d5c-a6ba-68416d7ed260

https://github.com/Archotech/TTR24-Feedback/assets/140116455/96d6a9bc-2434-4103-b105-978f349af6eb

https://github.com/Archotech/TTR24-Feedback/assets/140116455/b1031a46-a940-4322-bd50-912dced75c02

https://github.com/Archotech/TTR24-Feedback/assets/140116455/ff979b46-50f6-4284-9ee5-5fa0a940254e

https://github.com/Archotech/TTR24-Feedback/assets/140116455/96c4fc22-ef24-4e2e-aea4-4cf223b7ad49

![ima6312ge](https://github.com/Archotech/TTR24-Feedback/assets/140116455/9ce37f00-c1b3-4a83-8d1d-4d97ae172f7a)

https://github.com/Archotech/TTR24-Feedback/assets/140116455/47f7736f-2c96-4e7f-889d-efd43583c84f

Лифт уезжает выше в вверху
В самой комнате портала лифт в нормальной позиции

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.407

**Comment by Sont3k** [comment]
Incorrect starting height parameter for a elevator, will be fixed
