### ISSUE TITLE
[Bug]: <Render issue>

### ISSUE THREAD

**Issue by belplaton** [Archotech/TTR24-Feedback#73]
### Steps To Reproduce

1. Windows 10
2. No matter
3. Просто играйте и рано или поздно будет возникать ошибка
4. 
![image](https://github.com/Archotech/TTR24-Feedback/assets/143908720/7c9b9065-d000-4d47-9a20-f65857c44888)
![Uploading image.png…]()

### Actual Behavior

Происходит ошибка в рендеринге, так как скорее всего генератор карты все еще плохо работает с системой прогрузки комнат (не настраивает), однако имеет частный характер, нужно смотреть.

### Expected Behavior

Не должно быть проблем с прогрузкой

### OS

Windows 10

### Version

0.5.407

**Comment by Sont3k** [comment]
Fixed in [#1226](https://github.com/Archotech/TTR24/issues/1226)
