### ISSUE TITLE
[Bug]: Можно "бежать спиной"

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#74]
### Steps To Reproduce

Идти спиной и спамить Shift

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/d33b939c-0291-4270-9825-7fc3ca7f0fbe

происходит отдаление камеры (Изменение FOV) Будто при беге вперед

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.407

### Additional Context

-

**Comment by Ex3cut4ble** [comment]
Fixed here: https://github.com/Archotech/TTR24/pull/1243

**Comment by Ex3cut4ble** [comment]
@Sont3k по какой-то причине я не могу прикрепить себя или пул-реквест по-нормальному, поэтому сделал так :)
просто поля серые и недоступные
![Image](https://github.com/Archotech/TTR24-Feedback/assets/74779811/7bf95918-4ca3-4ea5-a0df-5a7e93ea02e7)

**Comment by Ex3cut4ble** [comment]
@Sont3k у платона тоже нету возможности изменять эти данные

**Comment by Sont3k** [comment]
@Ex3cut4ble 
![Image](https://github.com/Archotech/TTR24-Feedback/assets/40692222/84950682-d14a-4e5f-a496-4a8e3c8e3bc7)
вот тут ветку крепить, чуть ниже
