### ISSUE TITLE
[Bug]: Fantom broken door

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#75]
### Steps To Reproduce

Попросить друга 173 сломать дверь

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/2edb507d-779c-4ffd-b817-8416b3b7afee

Для 173 дверь сломана (как видно по следам на двери) но для меня (д класса) не сломанна
Так же при открытии она не издает звуки

### OS

Windows 10

### Version

0.5.407

### Additional Context

-

**Comment by belplaton** [comment]
Проблема десинка генератора

**Comment by belplaton** [comment]
Либо же проблема работы нынешнего интерест менеджера, который прогружает коллайдеры обратно

**Comment by Sont3k** [comment]
[0.5.410 version]
Host - 173, Client - Human -> not reproduced (door destroyed on both sides)
Host - Human, Client - 173 - > not reproduced (door destroyed on both sides)

Requires additional check on latest version

**Comment by belplaton** [comment]
скорее всего интерест менеджер.

**Comment by Sont3k** [comment]
та может, но если даже у тестеров не повторяется, то можно ложить в Release Candidate
если снова увидим, то уже новую багу откроем

**Comment by DecafRx** [comment]
Никак не повторить
- Не протестировано

**Comment by DecafRx** [comment]
cant reproduce
