### ISSUE TITLE
[Bug]: Пропадают игроки из списка, и дюпаются там

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#78]
### Steps To Reproduce

Зайти на сервер с игроками
периодически смотреть список игроков во время игры

### Actual Behavior

Когда я подхожу ближе к каким либо игрокам, в списке они появляются, а иногда дублируются

https://github.com/Archotech/TTR24-Feedback/assets/140116455/26d6a592-fe95-4011-9f14-7bfb100a887b

https://github.com/Archotech/TTR24-Feedback/assets/140116455/3c481d0e-16a4-4e0f-a6f8-a4cc930bbee2

https://github.com/Archotech/TTR24-Feedback/assets/140116455/5447dd1a-f453-4a7c-ab63-98162183e1d2

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.407

**Comment by Sont3k** [comment]
Fixed not working unregister on dead player -> spectator transition that created alive players duplicate on after each player death
