### ISSUE TITLE
[Bug]: Items animations clip issue

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#79]
### Steps To Reproduce

Предметы из быстрых слотов появляются только при начале движения камеры
Взять предмет в руки из быстрого слота
подвигать камерой

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/e5909e3e-be5c-4d96-836e-08582e36e4f3

https://github.com/Archotech/TTR24-Feedback/assets/140116455/1a553664-9f73-4239-8c3d-35a72013d875

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.407

**Comment by Sont3k** [comment]
FPS animator had enabled culling
