### ISSUE TITLE
[Bug]: Мина спавнится за стеклом, ее невозможно подобрать

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#81]
### Steps To Reproduce

Найти нужную комнату ( на скриншоте)
Попробовать подобрать мину через стекло (она не подберется)

### Actual Behavior

![image](https://github.com/Archotech/TTR24-Feedback/assets/140116455/10bf9624-cd08-4107-9554-c7a0d8bb96fa)

### Expected Behavior

Спавн мины должен быть изменен

### OS

Windows 10

### Version

0.5.407

**Comment by AdobeFlex** [comment]
Не баг, особенность пропинга
