### ISSUE TITLE
Map Generation

### ISSUE THREAD

**Issue by Demro** [Archotech/TTR24-Feedback#82]
### Steps To Reproduce

1. Create and start a server.
2.  Wait till the round starts.
3. You'll check the bug.  

### Actual Behavior

The bugs sometimes appear in different rooms; it's a matter of investigating why they are created.

### Expected Behavior

Find and fix the map generation.

### OS

Windows <10

### Version

0.5.407

### Additional Context

[Map_bug.zip](https://github.com/user-attachments/files/15524208/Map_bug.zip)

### Contact information

demroil47@gmail.com

**Comment by Sont3k** [comment]
Rooms can spawn on top of each other somewhat (was reproduced in development environment)
Position check for a rooms would be investigated

**Comment by Sont3k** [comment]
After fixing missed addressables on new rooms issue haven't been reproduced even once, so leaving now for a further investigation

**Comment by Demro** [comment]
Here are more from other rounds

https://github.com/Archotech/TTR24-Feedback/assets/54320957/c2eca7f5-3607-4f48-bc55-158b7ff3fd66


https://github.com/Archotech/TTR24-Feedback/assets/54320957/e4601f64-c0a6-4610-9747-ce819ae5d542

**Comment by Sont3k** [comment]
Found an issue, map check can be passed in cases when rooms in a sector won't fully connected even when path from lobby to last sector exists

**Comment by Sont3k** [comment]
![Image](https://github.com/Archotech/TTR24-Feedback/assets/40692222/fe708bca-ae63-4e9e-88aa-2e589c3bf7c7)

Now Map will have much detailed path check
