### ISSUE TITLE
[Bug]: scp 009 и пистолет рядом невозможно подобрать

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#84]
### Steps To Reproduce

Попробовать подобрать 009 на его спавне (его комнате содержания) и пистолет рядом с ним

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/2d837b74-1275-4b4f-ad16-ec822fb01950

### Expected Behavior

-

### OS

Windows 10

### Version

0.5.408

### Additional Context

Баг под номером #76 был помечен как "пофикшеный" но он остался, только теперь нельзя даже пистолет подобрать

**Comment by Sont3k** [comment]
![Image](https://github.com/Archotech/TTR24-Feedback/assets/40692222/35765d37-0221-4385-b146-c57d6a1d1c8d)
![Image](https://github.com/Archotech/TTR24-Feedback/assets/40692222/039f12b2-07f9-4f26-b78d-41f6f6611fdc)

Заменил коллайдер у кейса на обычный бокс, потому что меш сильно выступал вверх и собой перекрывал предметы
