### ISSUE TITLE
[Bug]: Плохой пропинг новой комнаты

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#86]
### Steps To Reproduce

Зайти в новую комнату

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/9d34e5bd-4f55-4166-a9fc-87562ec22a47

### Expected Behavior

электрощиток должен иметь нормальную позицию

### OS

Windows 10

### Version

0.5.408

**Comment by AdobeFlex** [comment]
Исправлено, карты света будут подпечены

**Comment by DecafRx** [comment]
![image](https://github.com/Archotech/TTR24-Feedback/assets/140116455/031e0218-259a-4c58-91b9-1907dbbd5410)
Исправлено, но осталась тень

**Comment by AdobeFlex** [comment]
Исправлено, карты света подпечены
