### ISSUE TITLE
[Bug]: Любой устанавлеемый предмет можно дюпать

### ISSUE THREAD

**Issue by DecafRx** [Archotech/TTR24-Feedback#87]
### Steps To Reproduce

1перенести устанавлеемый предмет (будь то дорлокер или с4) в горячий слот (например слот 5)
2перенести любой другой предмет (например бинт) в горячий слот (например слот 4)
3 когда ты держишь С4 (или дорлокер) переключись на бинт (нажав по горячему слоту), и СРАЗУ ЖЕ поставь С4 (просто нажать на ЛКМ)
Считайте, вам одновременно надо нажать на переключение слота (на бинт) и ЛКМ (чтобы поставить предмет)
Если поймал тайминг (довольно простой) то у тебя все получилось

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/140116455/34121b29-c50c-43c5-acda-4f2829f1314c

https://github.com/Archotech/TTR24-Feedback/assets/140116455/f3feeb77-ce11-4a17-9ba8-6718a204d3b8

https://github.com/Archotech/TTR24-Feedback/assets/140116455/efb7522a-32d0-4101-a67c-36e0285a9045

Предмет ставится. но при этом остается у тебя в инвентаре

### Expected Behavior

Предмет должен пропадать из ивентаря

### OS

Windows 10

### Version

0.5.408

**Comment by Ex3cut4ble** [comment]
Fixed in https://github.com/Archotech/TTR24/pull/1244

**Comment by Ex3cut4ble** [comment]
если решение не окажется достаточно чистым, то можно подождать ревок инвентаря от Платона, и через какой-нибудь метод DeleteItemOfType() просто насильно удалять InstallableItem из инвентаря, и забить на проверку Engage слотов

**Comment by Ex3cut4ble** [comment]
Закрыто, т.к. скорее всего Платон переделает инвентарь настолько, что этот фикс он сам позже произведёт

**Comment by Ex3cut4ble** [comment]
Переделано, т.к. реворк инвентаря Платона будет после релиза новой версии

**Comment by DecafRx** [comment]
Fixed

**Comment by DecafRx** [comment]
Пофикшено старый способ выявить этот баг
Но он воспроизводится еще одним способом:


https://github.com/user-attachments/assets/131c9ba8-a2ba-4341-a1e3-c235b995794d

Надо сначала выкинуть (на g), и в ту же секунду поставить

Наверное принцип действия (ну или фундамент бага, хз как это назвать) связан с #101
