### ISSUE TITLE
[Bug]: Mines move behind the wall texture

### ISSUE THREAD

**Issue by NekoHikka** [Archotech/TTR24-Feedback#88]
### Steps To Reproduce

Put a C4 or a mine on the lift door.

### Actual Behavior

I'm confused as to why it works with the lift but not with normal doors.

### Expected Behavior

It should fall down just like if you do it with the doors and close them.
This is what a bug looks like:
https://github.com/Archotech/TTR24-Feedback/assets/153106198/21d58f97-573b-4f71-bb97-e3b2f91fb038

This is what it looks like if you do the same thing with a normal door:

https://github.com/Archotech/TTR24-Feedback/assets/153106198/d032d2d7-e52c-4400-a056-0a0e7765c5bc

### OS

Windows <10

### Version

v0.5.408

### Contact information

NekoHikka

**Comment by belplaton** [comment]
Ветка с аналогичным названием:
Mines-move-behind-the-wall-texture

**Comment by Sont3k** [comment]
@belplaton pull request не создан
