### ISSUE TITLE
[Bug]: Баг с тенью

### ISSUE THREAD

**Issue by NekoHikka** [Archotech/TTR24-Feedback#94]
### Steps To Reproduce

Встать в этом месте и неможко двигатся что бы просто увидить этот баг с тенью

### Actual Behavior

Раньше вроде как был в этом месте я заливал бог что не видно 3D тень такая же но тела теперь тут видно только шмотки одетые.

https://github.com/Archotech/TTR24-Feedback/assets/153106198/077e9759-9a6d-43a2-b222-a0770f3ddd71

### Expected Behavior

.

### OS

Windows <10

### Version

v0.5.409

### Contact information

NekoHikka

**Comment by AdobeFlex** [comment]
Пофикшено
