### ISSUE TITLE
[Bug]: Mine position and Mine trigger action

### ISSUE THREAD

**Issue by NekoHikka** [Archotech/TTR24-Feedback#95]
### Steps To Reproduce

Просто найти это место и лицезреть.

### Actual Behavior

Прохожу мимо мин с датчиком движения и они не взрываются.
Так-же с определенной стороны видно что лучи от датчиков резко обрываются возле стены можно было бы поменять их месторасположение.
Так-же я проходил просто мимо них вне записи и они так-же не реагировали.

https://github.com/Archotech/TTR24-Feedback/assets/153106198/0aca20b8-e1f1-4b0a-a87b-b1b8bdb14ad5

### Expected Behavior

Мины будут взрываться и правильно красивенько стоять.

### OS

Windows <10

### Version

v0.5.409

### Contact information

NekoHikka

**Comment by DecafRx** [comment]
Мины теперь просто невидимые 



https://github.com/Archotech/TTR24-Feedback/assets/140116455/fd38a4a7-89c2-487a-9fb4-5da039a045b8



https://github.com/Archotech/TTR24-Feedback/assets/140116455/e5e140ce-bf58-4e08-9421-74a60fbcacc4

**Comment by Sont3k** [comment]
Mines invisibility not related to issue in this task so it's moved to separate issue
This issue is closed
