### ISSUE TITLE
[Bug]: Bring and Goto are not working correctly

### ISSUE THREAD

**Issue by RiFFyg** [Archotech/TTR24-Feedback#99]
### Steps To Reproduce

1. Open the command prompt
2. Register the command

### Actual Behavior

https://github.com/Archotech/TTR24-Feedback/assets/173466992/b29b58c5-c12e-4547-991d-f892b9f87322

![image](https://github.com/Archotech/TTR24-Feedback/assets/173466992/0e554216-abd8-4eb8-85e8-d1905965dc61)
The player disintegrate.

### Expected Behavior

Player Teleportation

### OS

Windows 11

### Version

0.5.409

**Comment by DecafRx** [comment]
![image](https://github.com/Archotech/TTR24-Feedback/assets/140116455/4c1da8a9-8139-4683-9dcd-09d348c789b4)
